#!/usr/bin/env python

import rospy
from speed_control.msg import Speed

def callback(data):
	rospy.loginfo("Received data:\n Velocity:%f, Direction:%f") % (data.velocity,data.direction)

def listener():
	rospy.init_node("signal_generator")
	rospy.Subscriber("wheelchair_speed",Speed,callback)

	rospy.spin()

if __name__ == "__main__":
	listener()
