// Generated by gencpp from file speed_control/Speed.msg
// DO NOT EDIT!


#ifndef SPEED_CONTROL_MESSAGE_SPEED_H
#define SPEED_CONTROL_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace speed_control
{
template <class ContainerAllocator>
struct Speed_
{
  typedef Speed_<ContainerAllocator> Type;

  Speed_()
    : header()
    , velocity(0.0)
    , direction(0.0)  {
    }
  Speed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _direction_type;
  _direction_type direction;




  typedef boost::shared_ptr< ::speed_control::Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speed_control::Speed_<ContainerAllocator> const> ConstPtr;

}; // struct Speed_

typedef ::speed_control::Speed_<std::allocator<void> > Speed;

typedef boost::shared_ptr< ::speed_control::Speed > SpeedPtr;
typedef boost::shared_ptr< ::speed_control::Speed const> SpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speed_control::Speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speed_control::Speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace speed_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'speed_control': ['/home/yaphes/river_ws/src/speed_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::speed_control::Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speed_control::Speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_control::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speed_control::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_control::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speed_control::Speed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speed_control::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4239fdcb6f7db4138bc6a5c8d84c4508";
  }

  static const char* value(const ::speed_control::Speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4239fdcb6f7db413ULL;
  static const uint64_t static_value2 = 0x8bc6a5c8d84c4508ULL;
};

template<class ContainerAllocator>
struct DataType< ::speed_control::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speed_control/Speed";
  }

  static const char* value(const ::speed_control::Speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speed_control::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 velocity\n\
float32 direction\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::speed_control::Speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speed_control::Speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speed_control::Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speed_control::Speed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEED_CONTROL_MESSAGE_SPEED_H
